spring.application.name=minimarket-plus-eft
server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

minimarket.security.jwt-secret=MiniMarketPlusEftSecretKey2026ForJwtSigningAndValidation
minimarket.security.jwt-expiration-minutes=120
