spring.application.name=petcare-pro-security
server.port=8082

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:petcaredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
security.jwt.expiration-seconds=3600
security.jwt.secret=petcare-pro-backend2-jwt-secret-key-super-segura-2026-demo